
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.dndcraft.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.dndcraft.item.ZwoHandedClubItem;
import net.mcreator.dndcraft.item.WarHammerItem;
import net.mcreator.dndcraft.item.UltimatePotionofhealingItem;
import net.mcreator.dndcraft.item.TwoHandedhammerItem;
import net.mcreator.dndcraft.item.TwoHandedClaymoreItem;
import net.mcreator.dndcraft.item.TwoHandedAxeItem;
import net.mcreator.dndcraft.item.TwoHandedAdamantiumHammerItem;
import net.mcreator.dndcraft.item.TwoHandedAdamantiumClaymoreItem;
import net.mcreator.dndcraft.item.TwoHandedAdamantiumAxeItem;
import net.mcreator.dndcraft.item.SuperiorPotionofHealingItem;
import net.mcreator.dndcraft.item.SpearItem;
import net.mcreator.dndcraft.item.SoapItem;
import net.mcreator.dndcraft.item.SickleItem;
import net.mcreator.dndcraft.item.ScrapsheetItem;
import net.mcreator.dndcraft.item.ScimitarItem;
import net.mcreator.dndcraft.item.RustyMaceItem;
import net.mcreator.dndcraft.item.RawplatinumoreItem;
import net.mcreator.dndcraft.item.RawOwlbearMeatItem;
import net.mcreator.dndcraft.item.RawOrkBeefItem;
import net.mcreator.dndcraft.item.RawAdamantiumOreItem;
import net.mcreator.dndcraft.item.PotionofstronghealingItem;
import net.mcreator.dndcraft.item.Poisoneddagger2Item;
import net.mcreator.dndcraft.item.PoisonedDaggerItem;
import net.mcreator.dndcraft.item.PoisonVialItem;
import net.mcreator.dndcraft.item.PlainumingotItem;
import net.mcreator.dndcraft.item.OwlbearMeatStripeItem;
import net.mcreator.dndcraft.item.OwlbearDrumsticksItem;
import net.mcreator.dndcraft.item.OrksteaakItem;
import net.mcreator.dndcraft.item.MonsterDaggerItem;
import net.mcreator.dndcraft.item.MetalRodItem;
import net.mcreator.dndcraft.item.MagicscrollFirearrowItem;
import net.mcreator.dndcraft.item.MagicWandItem;
import net.mcreator.dndcraft.item.MaceItem;
import net.mcreator.dndcraft.item.LightHammerItem;
import net.mcreator.dndcraft.item.LightAdamantiumHammerItem;
import net.mcreator.dndcraft.item.IronPlateItem;
import net.mcreator.dndcraft.item.IronCoinItem;
import net.mcreator.dndcraft.item.HealPotionItem;
import net.mcreator.dndcraft.item.HarpyToothItem;
import net.mcreator.dndcraft.item.HarpySpearItem;
import net.mcreator.dndcraft.item.GoldCoinItem;
import net.mcreator.dndcraft.item.GoblinsBackpackItem;
import net.mcreator.dndcraft.item.GladiusItem;
import net.mcreator.dndcraft.item.GhostAxeItem;
import net.mcreator.dndcraft.item.FeywildItem;
import net.mcreator.dndcraft.item.DrumsItem;
import net.mcreator.dndcraft.item.DailyRationItem;
import net.mcreator.dndcraft.item.DaggerItem;
import net.mcreator.dndcraft.item.CopperCoinItem;
import net.mcreator.dndcraft.item.CookedOwlbearMeatItem;
import net.mcreator.dndcraft.item.CookedOrkBeefItem;
import net.mcreator.dndcraft.item.ClubItem;
import net.mcreator.dndcraft.item.ClaymoreItem;
import net.mcreator.dndcraft.item.BowitemItem;
import net.mcreator.dndcraft.item.BattleStaffItem;
import net.mcreator.dndcraft.item.BattleAxeItem;
import net.mcreator.dndcraft.item.BattalestafftwohandedItem;
import net.mcreator.dndcraft.item.BanjoItem;
import net.mcreator.dndcraft.item.AxItem;
import net.mcreator.dndcraft.item.AnimalFatItem;
import net.mcreator.dndcraft.item.AnimalBoneItem;
import net.mcreator.dndcraft.item.AdantiumIngotItem;
import net.mcreator.dndcraft.item.AdamantiumWarHammerItem;
import net.mcreator.dndcraft.item.AdamantiumUpgradeSmithingTemplateItem;
import net.mcreator.dndcraft.item.AdamantiumSpearItem;
import net.mcreator.dndcraft.item.AdamantiumSickleItem;
import net.mcreator.dndcraft.item.AdamantiumScimitarItem;
import net.mcreator.dndcraft.item.AdamantiumMaceItem;
import net.mcreator.dndcraft.item.AdamantiumGladiusItem;
import net.mcreator.dndcraft.item.AdamantiumDaggerItem;
import net.mcreator.dndcraft.item.AdamantiumCoinItem;
import net.mcreator.dndcraft.item.AdamantiumClaymoreItem;
import net.mcreator.dndcraft.item.AdamantiumBattleAxeItem;
import net.mcreator.dndcraft.item.AdamantiumAxItem;
import net.mcreator.dndcraft.DndCraftMod;

public class DndCraftModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, DndCraftMod.MODID);
	public static final RegistryObject<Item> DAGGER = REGISTRY.register("dagger", () -> new DaggerItem());
	public static final RegistryObject<Item> AX = REGISTRY.register("ax", () -> new AxItem());
	public static final RegistryObject<Item> ANIMAL_BONE = REGISTRY.register("animal_bone", () -> new AnimalBoneItem());
	public static final RegistryObject<Item> LIGHT_HAMMER = REGISTRY.register("light_hammer", () -> new LightHammerItem());
	public static final RegistryObject<Item> BATTLE_STAFF = REGISTRY.register("battle_staff", () -> new BattleStaffItem());
	public static final RegistryObject<Item> CLUB = REGISTRY.register("club", () -> new ClubItem());
	public static final RegistryObject<Item> IRON_PLATE = REGISTRY.register("iron_plate", () -> new IronPlateItem());
	public static final RegistryObject<Item> SPEAR = REGISTRY.register("spear", () -> new SpearItem());
	public static final RegistryObject<Item> MACE = REGISTRY.register("mace", () -> new MaceItem());
	public static final RegistryObject<Item> METAL_ROD = REGISTRY.register("metal_rod", () -> new MetalRodItem());
	public static final RegistryObject<Item> ZWO_HANDED_CLUB = REGISTRY.register("zwo_handed_club", () -> new ZwoHandedClubItem());
	public static final RegistryObject<Item> GLADIUS = REGISTRY.register("gladius", () -> new GladiusItem());
	public static final RegistryObject<Item> CLAYMORE = REGISTRY.register("claymore", () -> new ClaymoreItem());
	public static final RegistryObject<Item> TWO_HANDEDHAMMER = REGISTRY.register("two_handedhammer", () -> new TwoHandedhammerItem());
	public static final RegistryObject<Item> WAR_HAMMER = REGISTRY.register("war_hammer", () -> new WarHammerItem());
	public static final RegistryObject<Item> TWO_HANDED_AXE = REGISTRY.register("two_handed_axe", () -> new TwoHandedAxeItem());
	public static final RegistryObject<Item> BATTLE_AXE = REGISTRY.register("battle_axe", () -> new BattleAxeItem());
	public static final RegistryObject<Item> SOAP = REGISTRY.register("soap", () -> new SoapItem());
	public static final RegistryObject<Item> ANIMAL_FAT = REGISTRY.register("animal_fat", () -> new AnimalFatItem());
	public static final RegistryObject<Item> TWO_HANDED_CLAYMORE = REGISTRY.register("two_handed_claymore", () -> new TwoHandedClaymoreItem());
	public static final RegistryObject<Item> SCIMITAR = REGISTRY.register("scimitar", () -> new ScimitarItem());
	public static final RegistryObject<Item> GHOST_AXE = REGISTRY.register("ghost_axe", () -> new GhostAxeItem());
	public static final RegistryObject<Item> SICKLE = REGISTRY.register("sickle", () -> new SickleItem());
	public static final RegistryObject<Item> OGRE_SPAWN_EGG = REGISTRY.register("ogre_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.OGRE, -6586302, -12766940, new Item.Properties()));
	public static final RegistryObject<Item> ORK_SPAWN_EGG = REGISTRY.register("ork_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.ORK, -9149356, -13027015, new Item.Properties()));
	public static final RegistryObject<Item> ADANTIUM_ORE = block(DndCraftModBlocks.ADANTIUM_ORE);
	public static final RegistryObject<Item> ADANTIUM_INGOT = REGISTRY.register("adantium_ingot", () -> new AdantiumIngotItem());
	public static final RegistryObject<Item> RAW_ADAMANTIUM_ORE = REGISTRY.register("raw_adamantium_ore", () -> new RawAdamantiumOreItem());
	public static final RegistryObject<Item> ADAMANTIUM_DAGGER = REGISTRY.register("adamantium_dagger", () -> new AdamantiumDaggerItem());
	public static final RegistryObject<Item> ADAMANTIUM_AX = REGISTRY.register("adamantium_ax", () -> new AdamantiumAxItem());
	public static final RegistryObject<Item> ADAMANTIUM_CLAYMORE = REGISTRY.register("adamantium_claymore", () -> new AdamantiumClaymoreItem());
	public static final RegistryObject<Item> LIGHT_ADAMANTIUM_HAMMER = REGISTRY.register("light_adamantium_hammer", () -> new LightAdamantiumHammerItem());
	public static final RegistryObject<Item> ADAMANTIUM_SPEAR = REGISTRY.register("adamantium_spear", () -> new AdamantiumSpearItem());
	public static final RegistryObject<Item> ADAMANTIUM_MACE = REGISTRY.register("adamantium_mace", () -> new AdamantiumMaceItem());
	public static final RegistryObject<Item> ADAMANTIUM_GLADIUS = REGISTRY.register("adamantium_gladius", () -> new AdamantiumGladiusItem());
	public static final RegistryObject<Item> TWO_HANDED_ADAMANTIUM_HAMMER = REGISTRY.register("two_handed_adamantium_hammer", () -> new TwoHandedAdamantiumHammerItem());
	public static final RegistryObject<Item> ADAMANTIUM_WAR_HAMMER = REGISTRY.register("adamantium_war_hammer", () -> new AdamantiumWarHammerItem());
	public static final RegistryObject<Item> TWO_HANDED_ADAMANTIUM_AXE = REGISTRY.register("two_handed_adamantium_axe", () -> new TwoHandedAdamantiumAxeItem());
	public static final RegistryObject<Item> ADAMANTIUM_BATTLE_AXE = REGISTRY.register("adamantium_battle_axe", () -> new AdamantiumBattleAxeItem());
	public static final RegistryObject<Item> TWO_HANDED_ADAMANTIUM_CLAYMORE = REGISTRY.register("two_handed_adamantium_claymore", () -> new TwoHandedAdamantiumClaymoreItem());
	public static final RegistryObject<Item> ADAMANTIUM_SCIMITAR = REGISTRY.register("adamantium_scimitar", () -> new AdamantiumScimitarItem());
	public static final RegistryObject<Item> ADAMANTIUM_SICKLE = REGISTRY.register("adamantium_sickle", () -> new AdamantiumSickleItem());
	public static final RegistryObject<Item> ADAMANTIUM_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("adamantium_upgrade_smithing_template", () -> new AdamantiumUpgradeSmithingTemplateItem());
	public static final RegistryObject<Item> HARPY_SPAWN_EGG = REGISTRY.register("harpy_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.HARPY, -5202039, -12765385, new Item.Properties()));
	public static final RegistryObject<Item> HARPY_TOOTH = REGISTRY.register("harpy_tooth", () -> new HarpyToothItem());
	public static final RegistryObject<Item> HARPY_SPEAR = REGISTRY.register("harpy_spear", () -> new HarpySpearItem());
	public static final RegistryObject<Item> OWLBEAR_SPAWN_EGG = REGISTRY.register("owlbear_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.OWLBEAR, -13231862, -14872051, new Item.Properties()));
	public static final RegistryObject<Item> RAW_OWLBEAR_MEAT = REGISTRY.register("raw_owlbear_meat", () -> new RawOwlbearMeatItem());
	public static final RegistryObject<Item> COOKED_OWLBEAR_MEAT = REGISTRY.register("cooked_owlbear_meat", () -> new CookedOwlbearMeatItem());
	public static final RegistryObject<Item> MIMIC_SPAWN_EGG = REGISTRY.register("mimic_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.MIMIC, -9157089, -9764864, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_SPAWN_EGG = REGISTRY.register("goblin_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.GOBLIN, -12837105, -18432, new Item.Properties()));
	public static final RegistryObject<Item> MONSTER_DAGGER = REGISTRY.register("monster_dagger", () -> new MonsterDaggerItem());
	public static final RegistryObject<Item> GOBLINS_BACKPACK = REGISTRY.register("goblins_backpack", () -> new GoblinsBackpackItem());
	public static final RegistryObject<Item> GOBLIN_CHIEF_SPAWN_EGG = REGISTRY.register("goblin_chief_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.GOBLIN_CHIEF, -14415864, -18432, new Item.Properties()));
	public static final RegistryObject<Item> COOKED_OWLBEAR_MEAT_BLOCK = block(DndCraftModBlocks.COOKED_OWLBEAR_MEAT_BLOCK);
	public static final RegistryObject<Item> RAW_ORK_BEEF = REGISTRY.register("raw_ork_beef", () -> new RawOrkBeefItem());
	public static final RegistryObject<Item> COOKED_ORK_BEEF = REGISTRY.register("cooked_ork_beef", () -> new CookedOrkBeefItem());
	public static final RegistryObject<Item> COPPER_COIN = REGISTRY.register("copper_coin", () -> new CopperCoinItem());
	public static final RegistryObject<Item> IRON_COIN = REGISTRY.register("iron_coin", () -> new IronCoinItem());
	public static final RegistryObject<Item> GOLD_COIN = REGISTRY.register("gold_coin", () -> new GoldCoinItem());
	public static final RegistryObject<Item> ADAMANTIUM_COIN = REGISTRY.register("adamantium_coin", () -> new AdamantiumCoinItem());
	public static final RegistryObject<Item> RUSTY_MACE = REGISTRY.register("rusty_mace", () -> new RustyMaceItem());
	public static final RegistryObject<Item> BATTALESTAFFTWOHANDED = REGISTRY.register("battalestafftwohanded", () -> new BattalestafftwohandedItem());
	public static final RegistryObject<Item> BANJO = REGISTRY.register("banjo", () -> new BanjoItem());
	public static final RegistryObject<Item> MAGIC_WAND = REGISTRY.register("magic_wand", () -> new MagicWandItem());
	public static final RegistryObject<Item> POISONED_DAGGER = REGISTRY.register("poisoned_dagger", () -> new PoisonedDaggerItem());
	public static final RegistryObject<Item> COATED_POISONED_DAGGER = REGISTRY.register("coated_poisoned_dagger", () -> new Poisoneddagger2Item());
	public static final RegistryObject<Item> HEAL_POTION = REGISTRY.register("heal_potion", () -> new HealPotionItem());
	public static final RegistryObject<Item> POTIONOFSTRONGHEALING = REGISTRY.register("potionofstronghealing", () -> new PotionofstronghealingItem());
	public static final RegistryObject<Item> SUPERIOR_POTIONOF_HEALING = REGISTRY.register("superior_potionof_healing", () -> new SuperiorPotionofHealingItem());
	public static final RegistryObject<Item> ULTIMATE_POTIONOFHEALING = REGISTRY.register("ultimate_potionofhealing", () -> new UltimatePotionofhealingItem());
	public static final RegistryObject<Item> POISON_VIAL = REGISTRY.register("poison_vial", () -> new PoisonVialItem());
	public static final RegistryObject<Item> OCHERJELLY_SPAWN_EGG = REGISTRY.register("ocherjelly_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.OCHERJELLY, -1713144, -6322651, new Item.Properties()));
	public static final RegistryObject<Item> RAW_OWLBEARMEAT_BLOCK = block(DndCraftModBlocks.RAW_OWLBEARMEAT_BLOCK);
	public static final RegistryObject<Item> INVISIBLE_STALKER_SPAWN_EGG = REGISTRY.register("invisible_stalker_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.INVISIBLE_STALKER, -7160382, -1, new Item.Properties()));
	public static final RegistryObject<Item> BASILISK_SPAWN_EGG = REGISTRY.register("basilisk_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.BASILISK, -12575973, -14211018, new Item.Properties()));
	public static final RegistryObject<Item> COOKEDOWLBEARMEATBLOCK_2 = block(DndCraftModBlocks.COOKEDOWLBEARMEATBLOCK_2);
	public static final RegistryObject<Item> COOKEDOWLBEARMEATBLOCK_3 = block(DndCraftModBlocks.COOKEDOWLBEARMEATBLOCK_3);
	public static final RegistryObject<Item> COOKEDOWLBEARMEATBLOCK_4 = block(DndCraftModBlocks.COOKEDOWLBEARMEATBLOCK_4);
	public static final RegistryObject<Item> OWLBEAR_MEAT_STRIPE = REGISTRY.register("owlbear_meat_stripe", () -> new OwlbearMeatStripeItem());
	public static final RegistryObject<Item> PLATINUM_ORE = block(DndCraftModBlocks.PLATINUM_ORE);
	public static final RegistryObject<Item> RAWPLATINUMORE = REGISTRY.register("rawplatinumore", () -> new RawplatinumoreItem());
	public static final RegistryObject<Item> PLAINUMINGOT = REGISTRY.register("plainumingot", () -> new PlainumingotItem());
	public static final RegistryObject<Item> MAGICSCROLL_FIREARROW = REGISTRY.register("magicscroll_firearrow", () -> new MagicscrollFirearrowItem());
	public static final RegistryObject<Item> SCRAPSHEET = REGISTRY.register("scrapsheet", () -> new ScrapsheetItem());
	public static final RegistryObject<Item> SCRAPBLOCK = block(DndCraftModBlocks.SCRAPBLOCK);
	public static final RegistryObject<Item> DRUMS = REGISTRY.register("drums", () -> new DrumsItem());
	public static final RegistryObject<Item> WARG_SPAWN_EGG = REGISTRY.register("warg_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.WARG, -3562105, -10333879, new Item.Properties()));
	public static final RegistryObject<Item> BOWITEM = REGISTRY.register("bowitem", () -> new BowitemItem());
	public static final RegistryObject<Item> COOK_SPAWN_EGG = REGISTRY.register("cook_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.COOK, -2969733, -11849188, new Item.Properties()));
	public static final RegistryObject<Item> DAILY_RATION = REGISTRY.register("daily_ration", () -> new DailyRationItem());
	public static final RegistryObject<Item> OWLBEAR_DRUMSTICKS = REGISTRY.register("owlbear_drumsticks", () -> new OwlbearDrumsticksItem());
	public static final RegistryObject<Item> ORKSTEAAK = REGISTRY.register("orksteaak", () -> new OrksteaakItem());
	public static final RegistryObject<Item> GHOUL_SPAWN_EGG = REGISTRY.register("ghoul_spawn_egg", () -> new ForgeSpawnEggItem(DndCraftModEntities.GHOUL, -16724788, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> FEYWILD = REGISTRY.register("feywild", () -> new FeywildItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
