/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.dcc.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.dcc.item.ZwoHandedClubItem;
import net.mcreator.dcc.item.WarHammerItem;
import net.mcreator.dcc.item.UltimatePotionofhealingItem;
import net.mcreator.dcc.item.TwoHandedhammerItem;
import net.mcreator.dcc.item.TwoHandedClaymoreItem;
import net.mcreator.dcc.item.TwoHandedAxeItem;
import net.mcreator.dcc.item.TwoHandedAdamantiumHammerItem;
import net.mcreator.dcc.item.TwoHandedAdamantiumClaymoreItem;
import net.mcreator.dcc.item.TwoHandedAdamantiumAxeItem;
import net.mcreator.dcc.item.SuperiorPotionofHealingItem;
import net.mcreator.dcc.item.SpearItem;
import net.mcreator.dcc.item.SoapItem;
import net.mcreator.dcc.item.SilverIngotItem;
import net.mcreator.dcc.item.SilverCoinItem;
import net.mcreator.dcc.item.SickleItem;
import net.mcreator.dcc.item.ScrapsheetItem;
import net.mcreator.dcc.item.ScimitarItem;
import net.mcreator.dcc.item.RustyMaceItem;
import net.mcreator.dcc.item.RawplatinumoreItem;
import net.mcreator.dcc.item.RawSilverOreItem;
import net.mcreator.dcc.item.RawOwlbearMeatItem;
import net.mcreator.dcc.item.RawOrkBeefItem;
import net.mcreator.dcc.item.RawAdamantiumOreItem;
import net.mcreator.dcc.item.PotionofstronghealingItem;
import net.mcreator.dcc.item.Poisoneddagger2Item;
import net.mcreator.dcc.item.PoisonedDaggerItem;
import net.mcreator.dcc.item.PoisonVialItem;
import net.mcreator.dcc.item.PlatinCoinItem;
import net.mcreator.dcc.item.PlainumingotItem;
import net.mcreator.dcc.item.OwlbearMeatStripeItem;
import net.mcreator.dcc.item.OwlbearDrumsticksItem;
import net.mcreator.dcc.item.OrksteaakItem;
import net.mcreator.dcc.item.MonsterDaggerItem;
import net.mcreator.dcc.item.MetalRodItem;
import net.mcreator.dcc.item.MagicscrollFirearrowItem;
import net.mcreator.dcc.item.MagicWandItem;
import net.mcreator.dcc.item.MaceItem;
import net.mcreator.dcc.item.LightHammerItem;
import net.mcreator.dcc.item.LightAdamantiumHammerItem;
import net.mcreator.dcc.item.IronPlateItem;
import net.mcreator.dcc.item.HealPotionItem;
import net.mcreator.dcc.item.HarpyToothItem;
import net.mcreator.dcc.item.HarpySpearItem;
import net.mcreator.dcc.item.GoldCoinItem;
import net.mcreator.dcc.item.GoblinsBackpackItem;
import net.mcreator.dcc.item.GlimmerleafFruitItem;
import net.mcreator.dcc.item.GladiusItem;
import net.mcreator.dcc.item.GhostAxeItem;
import net.mcreator.dcc.item.DrumsItem;
import net.mcreator.dcc.item.DailyRationItem;
import net.mcreator.dcc.item.DaggerItem;
import net.mcreator.dcc.item.CopperCoinItem;
import net.mcreator.dcc.item.CookedOwlbearMeatItem;
import net.mcreator.dcc.item.CookedOrkBeefItem;
import net.mcreator.dcc.item.ClubItem;
import net.mcreator.dcc.item.ClaymoreItem;
import net.mcreator.dcc.item.BattleStaffItem;
import net.mcreator.dcc.item.BattleAxeItem;
import net.mcreator.dcc.item.BattalestafftwohandedItem;
import net.mcreator.dcc.item.BanjoItem;
import net.mcreator.dcc.item.AxItem;
import net.mcreator.dcc.item.AnimalFatItem;
import net.mcreator.dcc.item.AnimalBoneItem;
import net.mcreator.dcc.item.AdantiumIngotItem;
import net.mcreator.dcc.item.AdamantiumWarHammerItem;
import net.mcreator.dcc.item.AdamantiumUpgradeSmithingTemplateItem;
import net.mcreator.dcc.item.AdamantiumSpearItem;
import net.mcreator.dcc.item.AdamantiumSickleItem;
import net.mcreator.dcc.item.AdamantiumScimitarItem;
import net.mcreator.dcc.item.AdamantiumMaceItem;
import net.mcreator.dcc.item.AdamantiumGladiusItem;
import net.mcreator.dcc.item.AdamantiumDaggerItem;
import net.mcreator.dcc.item.AdamantiumClaymoreItem;
import net.mcreator.dcc.item.AdamantiumBattleAxeItem;
import net.mcreator.dcc.item.AdamantiumAxItem;
import net.mcreator.dcc.DccMod;

public class DccModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(DccMod.MODID);
	public static final DeferredItem<Item> DAGGER = REGISTRY.register("dagger", DaggerItem::new);
	public static final DeferredItem<Item> AX = REGISTRY.register("ax", AxItem::new);
	public static final DeferredItem<Item> ANIMAL_BONE = REGISTRY.register("animal_bone", AnimalBoneItem::new);
	public static final DeferredItem<Item> LIGHT_HAMMER = REGISTRY.register("light_hammer", LightHammerItem::new);
	public static final DeferredItem<Item> BATTLE_STAFF = REGISTRY.register("battle_staff", BattleStaffItem::new);
	public static final DeferredItem<Item> CLUB = REGISTRY.register("club", ClubItem::new);
	public static final DeferredItem<Item> IRON_PLATE = REGISTRY.register("iron_plate", IronPlateItem::new);
	public static final DeferredItem<Item> SPEAR = REGISTRY.register("spear", SpearItem::new);
	public static final DeferredItem<Item> MACE = REGISTRY.register("mace", MaceItem::new);
	public static final DeferredItem<Item> METAL_ROD = REGISTRY.register("metal_rod", MetalRodItem::new);
	public static final DeferredItem<Item> ZWO_HANDED_CLUB = REGISTRY.register("zwo_handed_club", ZwoHandedClubItem::new);
	public static final DeferredItem<Item> GLADIUS = REGISTRY.register("gladius", GladiusItem::new);
	public static final DeferredItem<Item> CLAYMORE = REGISTRY.register("claymore", ClaymoreItem::new);
	public static final DeferredItem<Item> TWO_HANDEDHAMMER = REGISTRY.register("two_handedhammer", TwoHandedhammerItem::new);
	public static final DeferredItem<Item> WAR_HAMMER = REGISTRY.register("war_hammer", WarHammerItem::new);
	public static final DeferredItem<Item> TWO_HANDED_AXE = REGISTRY.register("two_handed_axe", TwoHandedAxeItem::new);
	public static final DeferredItem<Item> BATTLE_AXE = REGISTRY.register("battle_axe", BattleAxeItem::new);
	public static final DeferredItem<Item> SOAP = REGISTRY.register("soap", SoapItem::new);
	public static final DeferredItem<Item> ANIMAL_FAT = REGISTRY.register("animal_fat", AnimalFatItem::new);
	public static final DeferredItem<Item> TWO_HANDED_CLAYMORE = REGISTRY.register("two_handed_claymore", TwoHandedClaymoreItem::new);
	public static final DeferredItem<Item> SCIMITAR = REGISTRY.register("scimitar", ScimitarItem::new);
	public static final DeferredItem<Item> GHOST_AXE = REGISTRY.register("ghost_axe", GhostAxeItem::new);
	public static final DeferredItem<Item> SICKLE = REGISTRY.register("sickle", SickleItem::new);
	public static final DeferredItem<Item> OGRE_SPAWN_EGG = REGISTRY.register("ogre_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.OGRE, -6586302, -12766940, new Item.Properties()));
	public static final DeferredItem<Item> ORK_SPAWN_EGG = REGISTRY.register("ork_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.ORK, -9149356, -13027015, new Item.Properties()));
	public static final DeferredItem<Item> ADANTIUM_ORE = block(DccModBlocks.ADANTIUM_ORE);
	public static final DeferredItem<Item> ADANTIUM_INGOT = REGISTRY.register("adantium_ingot", AdantiumIngotItem::new);
	public static final DeferredItem<Item> RAW_ADAMANTIUM_ORE = REGISTRY.register("raw_adamantium_ore", RawAdamantiumOreItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_DAGGER = REGISTRY.register("adamantium_dagger", AdamantiumDaggerItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_AX = REGISTRY.register("adamantium_ax", AdamantiumAxItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_CLAYMORE = REGISTRY.register("adamantium_claymore", AdamantiumClaymoreItem::new);
	public static final DeferredItem<Item> LIGHT_ADAMANTIUM_HAMMER = REGISTRY.register("light_adamantium_hammer", LightAdamantiumHammerItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_SPEAR = REGISTRY.register("adamantium_spear", AdamantiumSpearItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_MACE = REGISTRY.register("adamantium_mace", AdamantiumMaceItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_GLADIUS = REGISTRY.register("adamantium_gladius", AdamantiumGladiusItem::new);
	public static final DeferredItem<Item> TWO_HANDED_ADAMANTIUM_HAMMER = REGISTRY.register("two_handed_adamantium_hammer", TwoHandedAdamantiumHammerItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_WAR_HAMMER = REGISTRY.register("adamantium_war_hammer", AdamantiumWarHammerItem::new);
	public static final DeferredItem<Item> TWO_HANDED_ADAMANTIUM_AXE = REGISTRY.register("two_handed_adamantium_axe", TwoHandedAdamantiumAxeItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_BATTLE_AXE = REGISTRY.register("adamantium_battle_axe", AdamantiumBattleAxeItem::new);
	public static final DeferredItem<Item> TWO_HANDED_ADAMANTIUM_CLAYMORE = REGISTRY.register("two_handed_adamantium_claymore", TwoHandedAdamantiumClaymoreItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_SCIMITAR = REGISTRY.register("adamantium_scimitar", AdamantiumScimitarItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_SICKLE = REGISTRY.register("adamantium_sickle", AdamantiumSickleItem::new);
	public static final DeferredItem<Item> ADAMANTIUM_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("adamantium_upgrade_smithing_template", AdamantiumUpgradeSmithingTemplateItem::new);
	public static final DeferredItem<Item> HARPY_SPAWN_EGG = REGISTRY.register("harpy_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.HARPY, -5202039, -12765385, new Item.Properties()));
	public static final DeferredItem<Item> HARPY_TOOTH = REGISTRY.register("harpy_tooth", HarpyToothItem::new);
	public static final DeferredItem<Item> HARPY_SPEAR = REGISTRY.register("harpy_spear", HarpySpearItem::new);
	public static final DeferredItem<Item> OWLBEAR_SPAWN_EGG = REGISTRY.register("owlbear_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.OWLBEAR, -13231862, -14872051, new Item.Properties()));
	public static final DeferredItem<Item> RAW_OWLBEAR_MEAT = REGISTRY.register("raw_owlbear_meat", RawOwlbearMeatItem::new);
	public static final DeferredItem<Item> COOKED_OWLBEAR_MEAT = REGISTRY.register("cooked_owlbear_meat", CookedOwlbearMeatItem::new);
	public static final DeferredItem<Item> MIMIC_SPAWN_EGG = REGISTRY.register("mimic_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.MIMIC, -9157089, -9764864, new Item.Properties()));
	public static final DeferredItem<Item> GOBLIN_SPAWN_EGG = REGISTRY.register("goblin_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.GOBLIN, -12837105, -18432, new Item.Properties()));
	public static final DeferredItem<Item> MONSTER_DAGGER = REGISTRY.register("monster_dagger", MonsterDaggerItem::new);
	public static final DeferredItem<Item> GOBLINS_BACKPACK = REGISTRY.register("goblins_backpack", GoblinsBackpackItem::new);
	public static final DeferredItem<Item> GOBLIN_CHIEF_SPAWN_EGG = REGISTRY.register("goblin_chief_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.GOBLIN_CHIEF, -14415864, -18432, new Item.Properties()));
	public static final DeferredItem<Item> COOKED_OWLBEAR_MEAT_BLOCK = block(DccModBlocks.COOKED_OWLBEAR_MEAT_BLOCK);
	public static final DeferredItem<Item> RAW_ORK_BEEF = REGISTRY.register("raw_ork_beef", RawOrkBeefItem::new);
	public static final DeferredItem<Item> COOKED_ORK_BEEF = REGISTRY.register("cooked_ork_beef", CookedOrkBeefItem::new);
	public static final DeferredItem<Item> COPPER_COIN = REGISTRY.register("copper_coin", CopperCoinItem::new);
	public static final DeferredItem<Item> GOLD_COIN = REGISTRY.register("gold_coin", GoldCoinItem::new);
	public static final DeferredItem<Item> RUSTY_MACE = REGISTRY.register("rusty_mace", RustyMaceItem::new);
	public static final DeferredItem<Item> BATTALESTAFFTWOHANDED = REGISTRY.register("battalestafftwohanded", BattalestafftwohandedItem::new);
	public static final DeferredItem<Item> BANJO = REGISTRY.register("banjo", BanjoItem::new);
	public static final DeferredItem<Item> SPELLBOOK = REGISTRY.register("spellbook", MagicWandItem::new);
	public static final DeferredItem<Item> POISONED_DAGGER = REGISTRY.register("poisoned_dagger", PoisonedDaggerItem::new);
	public static final DeferredItem<Item> COATED_POISONED_DAGGER = REGISTRY.register("coated_poisoned_dagger", Poisoneddagger2Item::new);
	public static final DeferredItem<Item> HEAL_POTION = REGISTRY.register("heal_potion", HealPotionItem::new);
	public static final DeferredItem<Item> POTIONOFSTRONGHEALING = REGISTRY.register("potionofstronghealing", PotionofstronghealingItem::new);
	public static final DeferredItem<Item> SUPERIOR_POTIONOF_HEALING = REGISTRY.register("superior_potionof_healing", SuperiorPotionofHealingItem::new);
	public static final DeferredItem<Item> ULTIMATE_POTIONOFHEALING = REGISTRY.register("ultimate_potionofhealing", UltimatePotionofhealingItem::new);
	public static final DeferredItem<Item> POISON_VIAL = REGISTRY.register("poison_vial", PoisonVialItem::new);
	public static final DeferredItem<Item> OCHERJELLY_SPAWN_EGG = REGISTRY.register("ocherjelly_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.OCHERJELLY, -1713144, -6322651, new Item.Properties()));
	public static final DeferredItem<Item> RAW_OWLBEARMEAT_BLOCK = block(DccModBlocks.RAW_OWLBEARMEAT_BLOCK);
	public static final DeferredItem<Item> INVISIBLE_STALKER_SPAWN_EGG = REGISTRY.register("invisible_stalker_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.INVISIBLE_STALKER, -7160382, -1, new Item.Properties()));
	public static final DeferredItem<Item> BASILISK_SPAWN_EGG = REGISTRY.register("basilisk_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.BASILISK, -12575973, -14211018, new Item.Properties()));
	public static final DeferredItem<Item> COOKEDOWLBEARMEATBLOCK_2 = block(DccModBlocks.COOKEDOWLBEARMEATBLOCK_2);
	public static final DeferredItem<Item> COOKEDOWLBEARMEATBLOCK_3 = block(DccModBlocks.COOKEDOWLBEARMEATBLOCK_3);
	public static final DeferredItem<Item> COOKEDOWLBEARMEATBLOCK_4 = block(DccModBlocks.COOKEDOWLBEARMEATBLOCK_4);
	public static final DeferredItem<Item> OWLBEAR_MEAT_STRIPE = REGISTRY.register("owlbear_meat_stripe", OwlbearMeatStripeItem::new);
	public static final DeferredItem<Item> PLATINUM_ORE = block(DccModBlocks.PLATINUM_ORE);
	public static final DeferredItem<Item> RAWPLATINUMORE = REGISTRY.register("rawplatinumore", RawplatinumoreItem::new);
	public static final DeferredItem<Item> PLAINUMINGOT = REGISTRY.register("plainumingot", PlainumingotItem::new);
	public static final DeferredItem<Item> MAGICSCROLL_FIREARROW = REGISTRY.register("magicscroll_firearrow", MagicscrollFirearrowItem::new);
	public static final DeferredItem<Item> SCRAPSHEET = REGISTRY.register("scrapsheet", ScrapsheetItem::new);
	public static final DeferredItem<Item> SCRAPBLOCK = block(DccModBlocks.SCRAPBLOCK);
	public static final DeferredItem<Item> DRUMS = REGISTRY.register("drums", DrumsItem::new);
	public static final DeferredItem<Item> WARG_SPAWN_EGG = REGISTRY.register("warg_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.WARG, -3562105, -10333879, new Item.Properties()));
	public static final DeferredItem<Item> COOK_SPAWN_EGG = REGISTRY.register("cook_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.COOK, -2969733, -11849188, new Item.Properties()));
	public static final DeferredItem<Item> DAILY_RATION = REGISTRY.register("daily_ration", DailyRationItem::new);
	public static final DeferredItem<Item> OWLBEAR_DRUMSTICKS = REGISTRY.register("owlbear_drumsticks", OwlbearDrumsticksItem::new);
	public static final DeferredItem<Item> ORKSTEAAK = REGISTRY.register("orksteaak", OrksteaakItem::new);
	public static final DeferredItem<Item> GHOUL_SPAWN_EGG = REGISTRY.register("ghoul_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.GHOUL, -16724788, -10066330, new Item.Properties()));
	public static final DeferredItem<Item> VINES_SPAWN_EGG = REGISTRY.register("vines_spawn_egg", () -> new DeferredSpawnEggItem(DccModEntities.VINES, -1, -1, new Item.Properties()));
	public static final DeferredItem<Item> PLATIN_COIN = REGISTRY.register("platin_coin", PlatinCoinItem::new);
	public static final DeferredItem<Item> SILVER_COIN = REGISTRY.register("silver_coin", SilverCoinItem::new);
	public static final DeferredItem<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", SilverIngotItem::new);
	public static final DeferredItem<Item> RAW_SILVER_ORE = REGISTRY.register("raw_silver_ore", RawSilverOreItem::new);
	public static final DeferredItem<Item> SILVER_ORE = block(DccModBlocks.SILVER_ORE);
	public static final DeferredItem<Item> DEEPSLATE_SILVER_ORE = block(DccModBlocks.DEEPSLATE_SILVER_ORE);
	public static final DeferredItem<Item> GLIMMER_LEAVES = block(DccModBlocks.GLIMMER_LEAVES);
	public static final DeferredItem<Item> GLIMMERLEAF_FRUIT = REGISTRY.register("glimmerleaf_fruit", GlimmerleafFruitItem::new);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}